"""Martini pipeline analysis utilities: MDP audit, composition coverage, system summaries."""
from __future__ import annotations

import json
import os
import re
import subprocess
from collections import Counter
from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping, Sequence

_DEFAULT_SKIP_KEYS: frozenset[str] = frozenset({
    "gen-seed", "ld-seed", "tinit", "init-step", "simulation-part",
})

_STAGE_SOURCES: dict[str, tuple[str, str]] = {
    "run":           ("run.mdp",                           "mdp"),
    "equilibration": ("equilibration/martini_eq.tpr",      "tpr"),
    "minimization":  ("minimization/martini_em.tpr",       "tpr"),
}


# ---------------------------------------------------------------------------
# Internal parsing helpers
# ---------------------------------------------------------------------------

def _canonicalise_key(key: str) -> str:
    """Lowercase and replace underscores with hyphens to unify mdp vs tpr key styles."""
    return key.strip().lower().replace("_", "-")


def _normalise_value(value: str) -> str:
    """Strip inline comments and collapse whitespace."""
    value = value.split(";")[0]
    return " ".join(value.split())


def _parse_mdp_file(path: str | os.PathLike) -> dict[str, str]:
    """Parse a GROMACS .mdp file into {canonical_key: normalised_value}."""
    result: dict[str, str] = {}
    with open(path) as fh:
        for line in fh:
            line = line.split(";")[0].strip()
            if not line or "=" not in line:
                continue
            key, _, value = line.partition("=")
            ck = _canonicalise_key(key)
            cv = _normalise_value(value)
            if ck:
                result[ck] = cv
    return result


def _dump_tpr_inputrec(tpr_path: str | os.PathLike, gmx_binary: str = "gmx") -> dict[str, str]:
    """Extract inputrec key-value pairs from a .tpr via `gmx dump -s`.

    Skips matrix/array-structured entries (lines without `=` on the value side,
    or whose key contains `(`).
    """
    try:
        proc = subprocess.run(
            [gmx_binary, "dump", "-s", str(tpr_path)],
            capture_output=True, text=True, timeout=60,
        )
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"GROMACS binary {gmx_binary!r} not found. "
            "Provide the correct binary via gmx_binary=."
        ) from exc
    if proc.returncode != 0:
        raise RuntimeError(
            f"gmx dump failed for {tpr_path} (exit {proc.returncode}):\n{proc.stderr[:2000]}"
        )

    result: dict[str, str] = {}
    in_inputrec = False
    for line in proc.stdout.splitlines():
        if line.startswith("inputrec:"):
            in_inputrec = True
            continue
        if in_inputrec:
            if line and not line[0].isspace():
                break
            stripped = line.strip()
            if not stripped or "=" not in stripped:
                continue
            key_part = stripped.split("=")[0]
            if "(" in key_part or "[" in key_part:
                continue
            key, _, value = stripped.partition("=")
            ck = _canonicalise_key(key)
            cv = _normalise_value(value)
            if ck:
                result[ck] = cv
    return result


def _mode(values: Sequence[str]) -> str:
    """Return the most-frequent value; tie broken by first appearance."""
    counter: Counter[str] = Counter()
    first_seen: dict[str, int] = {}
    for i, v in enumerate(values):
        counter[v] += 1
        if v not in first_seen:
            first_seen[v] = i
    return min(counter, key=lambda v: (-counter[v], first_seen[v]))


# ---------------------------------------------------------------------------
# Public dataclasses
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class MDPDeviation:
    system: str
    stage: str
    key: str
    value: str
    canonical: str


@dataclass(frozen=True)
class MDPStageAudit:
    stage: str
    n_systems: int
    canonical: Mapping[str, str]
    deviations: tuple[MDPDeviation, ...]
    missing_systems: tuple[str, ...]


@dataclass(frozen=True)
class MDPAuditReport:
    stages: Mapping[str, MDPStageAudit]

    @property
    def total_deviations(self) -> int:
        return sum(len(s.deviations) for s in self.stages.values())

    def to_freeze_json(self) -> str:
        """Machine-readable freeze record: {stage: {key: canonical_value}}."""
        freeze = {
            stage: dict(audit.canonical)
            for stage, audit in self.stages.items()
        }
        return json.dumps(freeze, indent=2, sort_keys=True)

    def to_markdown(self) -> str:
        lines: list[str] = [
            "# MDP Audit Report",
            "",
            "Auto-generated by `scripts/simulation/audit_mdps.py`.",
            f"Total unexpected deviations: **{self.total_deviations}**.",
            "",
        ]
        for stage, audit in self.stages.items():
            lines += [
                f"## Stage: `{stage}`",
                "",
                f"- Systems contributing: {audit.n_systems}",
                f"- Missing: {len(audit.missing_systems)}",
                f"- Deviations (excluding skip-keys): {len(audit.deviations)}",
                "",
            ]
            if audit.missing_systems:
                lines.append("**Missing systems:**")
                for s in audit.missing_systems:
                    lines.append(f"- `{s}`")
                lines.append("")

            lines += ["### Canonical parameter values", ""]
            lines += ["| Key | Value |", "| --- | --- |"]
            for k, v in sorted(audit.canonical.items()):
                lines.append(f"| `{k}` | `{v}` |")
            lines.append("")

            if audit.deviations:
                lines += ["### Deviations from canonical", ""]
                lines += ["| System | Key | Value | Canonical |", "| --- | --- | --- | --- |"]
                for d in audit.deviations:
                    lines.append(f"| `{d.system}` | `{d.key}` | `{d.value}` | `{d.canonical}` |")
                lines.append("")
            else:
                lines += ["### Deviations from canonical", "", "None.", ""]

        lines += _cross_stage_diff(self)
        return "\n".join(lines)


def _cross_stage_diff(report: MDPAuditReport) -> list[str]:
    """Produce a section comparing canonical values across stages for shared keys."""
    stage_names = list(report.stages)
    if len(stage_names) < 2:
        return []

    # Collect all keys appearing in at least 2 stages
    key_to_stages: dict[str, list[str]] = {}
    for stage, audit in report.stages.items():
        for k in audit.canonical:
            key_to_stages.setdefault(k, []).append(stage)
    shared_keys = sorted(k for k, stages in key_to_stages.items() if len(stages) >= 2)

    if not shared_keys:
        return []

    lines: list[str] = [
        "## Cross-stage parameter comparison",
        "",
        "Keys shared across at least two stages. Bold = value differs from the first stage.",
        "",
    ]
    header = "| Key | " + " | ".join(f"`{s}`" for s in stage_names) + " |"
    separator = "| --- |" + " --- |" * len(stage_names)
    lines += [header, separator]

    for key in shared_keys:
        values = []
        first_val = None
        for stage in stage_names:
            v = report.stages[stage].canonical.get(key, "—")
            if first_val is None and v != "—":
                first_val = v
            values.append(v)

        differs_any = len({v for v in values if v != "—"}) > 1
        row_vals = []
        for v in values:
            if differs_any and v not in ("—", first_val):
                row_vals.append(f"**`{v}`**")
            else:
                row_vals.append(f"`{v}`")

        lines.append("| `" + key + "` | " + " | ".join(row_vals) + " |")

    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# Core audit logic
# ---------------------------------------------------------------------------

def _collect_stage_data(
    systems_root: str | os.PathLike,
    stage: str,
    gmx_binary: str,
) -> tuple[dict[str, dict[str, str]], list[str]]:
    """Return (by_system, missing_systems) for one stage."""
    rel_path, fmt = _STAGE_SOURCES[stage]
    by_system: dict[str, dict[str, str]] = {}
    missing: list[str] = []

    systems_root = str(systems_root)
    for entry in sorted(os.listdir(systems_root)):
        system_dir = os.path.join(systems_root, entry)
        if not os.path.isdir(system_dir):
            continue
        source = os.path.join(system_dir, rel_path)
        if not os.path.exists(source):
            missing.append(entry)
            continue
        try:
            if fmt == "mdp":
                by_system[entry] = _parse_mdp_file(source)
            else:
                by_system[entry] = _dump_tpr_inputrec(source, gmx_binary)
        except (FileNotFoundError, RuntimeError):
            missing.append(entry)

    return by_system, missing


def _audit_stage(
    stage: str,
    by_system: dict[str, dict[str, str]],
    missing_systems: list[str],
    skip_keys: frozenset[str],
) -> MDPStageAudit:
    """Compute canonical values and deviations for one stage."""
    if not by_system:
        return MDPStageAudit(
            stage=stage, n_systems=0,
            canonical=MappingProxyType({}),
            deviations=(), missing_systems=tuple(sorted(missing_systems)),
        )

    # Collect all values per key across systems
    all_keys: set[str] = set()
    for kv in by_system.values():
        all_keys.update(kv)

    canonical: dict[str, str] = {}
    deviations: list[MDPDeviation] = []

    for key in sorted(all_keys):
        if key in skip_keys:
            continue
        values = [kv[key] for kv in by_system.values() if key in kv]
        if not values:
            continue
        canon = _mode(values)
        canonical[key] = canon
        for system, kv in by_system.items():
            v = kv.get(key)
            if v is not None and v != canon:
                deviations.append(MDPDeviation(
                    system=system, stage=stage, key=key, value=v, canonical=canon,
                ))

    return MDPStageAudit(
        stage=stage,
        n_systems=len(by_system),
        canonical=MappingProxyType(canonical),
        deviations=tuple(deviations),
        missing_systems=tuple(sorted(missing_systems)),
    )


def diff_mdps(
    systems_root: str | os.PathLike,
    *,
    stages: tuple[str, ...] = ("run", "equilibration", "minimization"),
    gmx_binary: str = "gmx",
    skip_keys: frozenset[str] = _DEFAULT_SKIP_KEYS,
) -> MDPAuditReport:
    """Audit MDP parameters across all systems under *systems_root*.

    For 'run' reads run.mdp directly; for 'equilibration' / 'minimization'
    recovers inputrec from the matching .tpr via ``gmx dump -s``.

    Returns an MDPAuditReport with per-stage canonical values and deviations.
    """
    stage_audits: dict[str, MDPStageAudit] = {}
    for stage in stages:
        by_system, missing = _collect_stage_data(systems_root, stage, gmx_binary)
        stage_audits[stage] = _audit_stage(stage, by_system, missing, skip_keys)

    return MDPAuditReport(stages=MappingProxyType(stage_audits))
